# Generated by Django 4.2.11 on 2024-04-22 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais", models.CharField(max_length=25)),
                ("nombre", models.CharField(max_length=25)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("telf", models.CharField(max_length=15)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registros.empresa",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Sitio",
            fields=[
                (
                    "PTICellID",
                    models.CharField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100)),
                (
                    "lat_nominal",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitud Nominal"
                    ),
                ),
                (
                    "lon_nominal",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitud Nominal"
                    ),
                ),
                ("altura", models.CharField(blank=True, max_length=10, null=True)),
                ("provincia", models.CharField(blank=True, max_length=25, null=True)),
                ("municipio", models.CharField(blank=True, max_length=25, null=True)),
                ("localidad", models.CharField(blank=True, max_length=25, null=True)),
                ("contador_llegadas", models.PositiveIntegerField(default=0)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sitios",
                        to="registros.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidato", models.CharField(blank=True, max_length=15)),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha"
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registros.sitio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registros.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Campo",
                "verbose_name_plural": "Registros Campo",
            },
        ),
    ]
