# Generated by Django 4.2.11 on 2024-04-08 15:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLlegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9)])),
                ('fecha_llegada', models.DateTimeField()),
                ('lat_llegada', models.FloatField(blank=True, null=True)),
                ('lon_llegada', models.FloatField(blank=True, null=True)),
                ('status_llegada', models.CharField(choices=[('ok', 'Llegada al lugar'), ('in', 'incidente'), ('no', 'No Llegada')], default='ok', max_length=10, verbose_name='Llegada')),
                ('imagen_llegada', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Adquisition Report',
                'verbose_name_plural': 'Site Adquisition Report',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=25)),
                ('empresa', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Pais Empresa',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telf', models.CharField(max_length=15)),
                ('pais_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.servicio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTICellID', models.CharField(max_length=15)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('lat_nominal', models.FloatField(blank=True, null=True, verbose_name='Latitud Nominal')),
                ('lon_nominal', models.FloatField(blank=True, null=True, verbose_name='Longitud Nominal')),
                ('altura', models.CharField(blank=True, max_length=10, null=True)),
                ('pais_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitios', to='registros.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSitioImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='fotografias/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitio_imagenes_candidato', to='registros.registrollegada')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitio_imagenes_sitio', to='registros.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitio_imagenes_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio_lat', models.FloatField(blank=True, null=True)),
                ('sitio_lon', models.FloatField(blank=True, null=True)),
                ('sitio_imagen', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('sitio_descripcion', models.TextField(blank=True, null=True)),
                ('candidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitio_candidato', to='registros.registrollegada')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitio_sitio', to='registros.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitio_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario_nombre_apellido', models.CharField(max_length=100)),
                ('propietario_born', models.DateTimeField()),
                ('propietario_ci', models.CharField(blank=True, max_length=15, null=True)),
                ('propietario_telf', models.CharField(max_length=15)),
                ('propietario_direccion', models.TextField(max_length=100)),
                ('propietario_estado_civil', models.BooleanField(default=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_candidato', to='registros.registrollegada')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_sitio', to='registros.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propiedad_rol', models.CharField(max_length=100)),
                ('propiedad_escritura', models.CharField(max_length=100)),
                ('propiedad_registro_civil', models.TextField(max_length=100)),
                ('propiedad_imagen', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('propiedad_descripcion', models.TextField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedad_candidato', to='registros.registrollegada')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedad_sitio', to='registros.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedad_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLocalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(blank=True, max_length=25, null=True)),
                ('municipio', models.CharField(blank=True, max_length=25, null=True)),
                ('localidad', models.CharField(blank=True, max_length=25, null=True)),
                ('energia_localidad', models.BooleanField(default=True)),
                ('imagen_maps', models.ImageField(blank=True, null=True, upload_to='sitios/gmaps')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_candidato', to='registros.registrollegada')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_sitio', to='registros.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registrollegada',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llegada_sitio', to='registros.sitio'),
        ),
        migrations.AddField(
            model_name='registrollegada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llegada_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegistioElectrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrico_lat', models.FloatField(blank=True, null=True)),
                ('electrico_lon', models.FloatField(blank=True, null=True)),
                ('electrico_no_poste', models.CharField(blank=True, max_length=10, null=True)),
                ('electrico_comentario', models.TextField(blank=True, null=True)),
                ('electrico_imagen1', models.ImageField(upload_to='sitios/')),
                ('electrico_imagen2', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrico_candidato', to='registros.registrollegada')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrico_sitio', to='registros.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrico_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
