# Generated by Django 4.2.11 on 2024-04-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidato",
            name="id",
        ),
        migrations.AlterField(
            model_name="candidato",
            name="candidato",
            field=models.CharField(
                blank=True, max_length=15, primary_key=True, serialize=False
            ),
        ),
    ]
