# Generated by Django 4.2.11 on 2024-04-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrositio',
            old_name='candidado',
            new_name='candidato',
        ),
    ]
