# Generated by Django 4.2.11 on 2024-04-25 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "Buscador", "verbose_name_plural": "Buscadores"},
        ),
    ]
