# Generated by Django 4.2.11 on 2024-04-26 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
    ]
