# Generated by Django 4.2.11 on 2024-04-27 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registros", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidato",
            name="usuario",
        ),
        migrations.AddField(
            model_name="registrollegada",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
