# Generated by Django 4.2.11 on 2024-04-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='imagen_llegada',
            field=models.ImageField(blank=True, null=True, upload_to='sitios/'),
        ),
    ]
