# Generated by Django 4.2.11 on 2024-04-18 04:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'Registro Campo', 'verbose_name_plural': 'Registros Campo'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': '1. Empresas'},
        ),
        migrations.AlterModelOptions(
            name='sitio',
            options={'verbose_name': 'Sitio', 'verbose_name_plural': '3. Sitios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': '2. Usuarios'},
        ),
        migrations.AddField(
            model_name='candidato',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registros.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='candidato',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='id',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrollegada',
            name='candidato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato'),
        ),
        migrations.CreateModel(
            name='RegistroSitioImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='fotografias/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
            options={
                'verbose_name': 'Imagen Sitio',
                'verbose_name_plural': 'Imagenes Sitios',
            },
        ),
        migrations.CreateModel(
            name='RegistroSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio_fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Visita')),
                ('sitio_lat', models.FloatField(blank=True, null=True, verbose_name='Latitud Torre')),
                ('sitio_lon', models.FloatField(blank=True, null=True, verbose_name='Longitud Torre')),
                ('sitio_imagen', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('sitio_descripcion', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
            options={
                'verbose_name': 'Registro Sitio',
                'verbose_name_plural': 'Registro Sitios',
            },
        ),
        migrations.CreateModel(
            name='RegistroPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario_nombre_apellido', models.CharField(max_length=100)),
                ('propietario_born', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('propietario_ci', models.CharField(blank=True, max_length=15, null=True, verbose_name='Documento de Identidad')),
                ('propietario_telf', models.CharField(max_length=15, verbose_name='Telefono de Contacto')),
                ('propietario_direccion', models.TextField(max_length=100, verbose_name='Direccion Domicilio')),
                ('propietario_estado_civil', models.BooleanField(default=True, verbose_name='Casado')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='RegistroPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propiedad_rol', models.CharField(max_length=100)),
                ('propiedad_escritura', models.CharField(max_length=100, verbose_name='Escritura')),
                ('propiedad_registro_civil', models.TextField(max_length=100, verbose_name='Registro Civil')),
                ('propiedad_imagen', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('propiedad_descripcion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='RegistroLocalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(blank=True, max_length=25, null=True)),
                ('municipio', models.CharField(blank=True, max_length=25, null=True)),
                ('localidad', models.CharField(blank=True, max_length=25, null=True)),
                ('energia_localidad', models.BooleanField(default=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='RegistioElectrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrico_lat', models.FloatField(blank=True, null=True, verbose_name='Latitud Poste')),
                ('electrico_lon', models.FloatField(blank=True, null=True, verbose_name='Longitud Poste')),
                ('electrico_no_poste', models.CharField(blank=True, max_length=10, null=True, verbose_name='Identificacion Poste')),
                ('electrico_comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('electrico_imagen1', models.ImageField(upload_to='sitios/', verbose_name='Imagen Poste')),
                ('electrico_imagen2', models.ImageField(blank=True, null=True, upload_to='sitios/', verbose_name='Imagen Electrico')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
        ),
    ]
