# Generated by Django 4.2.11 on 2024-04-27 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registros", "0002_remove_candidato_usuario_registrollegada_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrollegada",
            name="lat_llegada",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="registrollegada",
            name="lon_llegada",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="registrollegada",
            name="observaciones",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="registrollegada",
            name="status_llegada",
            field=models.CharField(
                choices=[("true", "Llegada"), ("false", "Incidente")],
                max_length=5,
                verbose_name="Estatus",
            ),
        ),
        migrations.AlterField(
            model_name="registrollegada",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
