# Generated by Django 4.2.11 on 2024-04-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_candidato_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropropiedad',
            name='propiedad_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
    ]
