# Generated by Django 4.2.11 on 2024-04-17 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_candidato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='candidato',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
