# Generated by Django 4.2.11 on 2024-04-22 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0002_remove_candidato_id_alter_candidato_candidato"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroLlegada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_llegada",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de llegada",
                    ),
                ),
                ("lat_llegada", models.FloatField(blank=True, null=True)),
                ("lon_llegada", models.FloatField(blank=True, null=True)),
                (
                    "status_llegada",
                    models.CharField(
                        choices=[
                            ("ok", "Llegada al lugar"),
                            ("in", "incidente"),
                            ("no", "No Llegada"),
                        ],
                        default="ok",
                        max_length=10,
                        verbose_name="Estatus",
                    ),
                ),
                (
                    "imagen_llegada",
                    models.ImageField(blank=True, null=True, upload_to="sitios/"),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "candidato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registros.candidato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Llegada Localidad",
                "verbose_name_plural": "Llegada Localidad",
            },
        ),
    ]
