# Generated by Django 4.2.11 on 2024-04-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_registrositio_sitio_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrositio',
            name='sitio_fecha',
        ),
    ]
