# Generated by Django 4.2.11 on 2024-04-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registropropiedad_propiedad_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='sitio',
            options={'verbose_name': 'Sitio', 'verbose_name_plural': 'Sitios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='candidato',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
