# Generated by Django 4.2.11 on 2024-04-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_candidato_candidato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': '1. Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
