# Generated by Django 4.2.11 on 2024-04-27 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registros", "0003_alter_registrollegada_lat_llegada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrolocalidad",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
