# Generated by Django 4.2.11 on 2024-04-07 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0004_rename_registro_registrocampo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLlegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateTimeField()),
                ('lat_llegada', models.FloatField(blank=True, null=True)),
                ('lon_llegada', models.FloatField(blank=True, null=True)),
                ('status_llegada', models.CharField(choices=[('ok', 'Llegada al lugar'), ('in', 'incidente'), ('no', 'No Llegada')], default='ok', max_length=10, verbose_name='Llegada')),
                ('imagen_llegada', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLocalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(blank=True, max_length=25, null=True)),
                ('municipio', models.CharField(blank=True, max_length=25, null=True)),
                ('localidad', models.CharField(blank=True, max_length=25, null=True)),
                ('energia_localidad', models.BooleanField(default=True)),
                ('imagen_maps', models.ImageField(blank=True, null=True, upload_to='sitios/gmaps')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=25)),
                ('empresa', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telf', models.CharField(max_length=15)),
                ('pais_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.servicio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sitio',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='sitio',
            name='pais',
        ),
        migrations.AlterField(
            model_name='sitio',
            name='lat_nominal',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud Nominal'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='lon_nominal',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud Nominal'),
        ),
        migrations.DeleteModel(
            name='RegistroCampo',
        ),
        migrations.AddField(
            model_name='registrolocalidad',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_localidad', to='registros.sitio'),
        ),
        migrations.AddField(
            model_name='registrolocalidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_localidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrollegada',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_llegada', to='registros.sitio'),
        ),
        migrations.AddField(
            model_name='registrollegada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_llegada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitio',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitios', to='registros.servicio'),
        ),
    ]
