# Generated by Django 4.2.11 on 2024-04-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_empresa_options_alter_sitio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
