# Generated by Django 4.2.11 on 2024-04-17 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_empresa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': '4. Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': '1. Empresas'},
        ),
        migrations.AlterModelOptions(
            name='sitio',
            options={'verbose_name': 'Sitio', 'verbose_name_plural': '3. Sitios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': '2. Usuarios'},
        ),
        migrations.CreateModel(
            name='RegistroLocalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(blank=True, max_length=25, null=True)),
                ('municipio', models.CharField(blank=True, max_length=25, null=True)),
                ('localidad', models.CharField(blank=True, max_length=25, null=True)),
                ('energia_localidad', models.BooleanField(default=True)),
                ('imagen_maps', models.ImageField(blank=True, null=True, upload_to='sitios/gmaps')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidad',
            },
        ),
    ]
