# Generated by Django 4.2.11 on 2024-04-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0004_alter_registrollegada_options_registrolocalidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrollegada",
            name="id",
        ),
        migrations.AlterField(
            model_name="registrollegada",
            name="candidato",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="registros.candidato",
            ),
        ),
    ]
