# Generated by Django 4.2.11 on 2024-04-08 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_remove_registrositio_sitio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrositio',
            name='sitio_fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
