# Generated by Django 4.2.11 on 2024-04-27 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0004_registrolocalidad_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrolocalidad",
            name="usuario",
        ),
    ]
