# Generated by Django 4.2.11 on 2024-04-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_candidato_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
