# Generated by Django 4.2.11 on 2024-04-22 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0005_remove_registrollegada_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroPropiedad",
            fields=[
                (
                    "candidato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="registros.candidato",
                    ),
                ),
                ("propiedad_rol", models.CharField(max_length=100, verbose_name="Rol")),
                (
                    "propiedad_escritura",
                    models.CharField(max_length=100, verbose_name="Escritura"),
                ),
                (
                    "propiedad_registro_civil",
                    models.TextField(max_length=100, verbose_name="Registro Civil"),
                ),
                (
                    "propiedad_imagen",
                    models.ImageField(blank=True, null=True, upload_to="sitios/"),
                ),
                (
                    "propiedad_descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Comentarios"),
                ),
            ],
            options={
                "verbose_name": "Propiedad",
                "verbose_name_plural": "Propiedades",
            },
        ),
        migrations.CreateModel(
            name="RegistroPropietario",
            fields=[
                (
                    "candidato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="registros.candidato",
                    ),
                ),
                (
                    "propietario_nombre_apellido",
                    models.CharField(max_length=100, verbose_name="Nombre y Apellido"),
                ),
                (
                    "propietario_born",
                    models.DateTimeField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "propietario_ci",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Documento de Identidad",
                    ),
                ),
                (
                    "propietario_telf",
                    models.CharField(
                        max_length=15, verbose_name="Telefono de Contacto"
                    ),
                ),
                (
                    "propietario_direccion",
                    models.TextField(
                        max_length=100, verbose_name="Direccion Domicilio"
                    ),
                ),
                (
                    "propietario_estado_civil",
                    models.BooleanField(default=True, verbose_name="Estado Civil"),
                ),
            ],
            options={
                "verbose_name": "Propietario",
                "verbose_name_plural": "Propietario",
            },
        ),
        migrations.CreateModel(
            name="RegistroSitio",
            fields=[
                (
                    "candidato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="registros.candidato",
                    ),
                ),
                (
                    "sitio_fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Visita",
                    ),
                ),
                (
                    "sitio_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitud Torre"
                    ),
                ),
                (
                    "sitio_lon",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitud Torre"
                    ),
                ),
                (
                    "sitio_imagen",
                    models.ImageField(blank=True, null=True, upload_to="sitios/"),
                ),
                (
                    "sitio_descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Comentarios"),
                ),
                (
                    "sitio_img_google",
                    models.ImageField(blank=True, null=True, upload_to="imgs_gmap/"),
                ),
            ],
            options={
                "verbose_name": "Registro Sitio",
                "verbose_name_plural": "Registro Sitios",
            },
        ),
        migrations.RemoveField(
            model_name="registrolocalidad",
            name="id",
        ),
        migrations.AlterField(
            model_name="registrolocalidad",
            name="candidato",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="registros.candidato",
            ),
        ),
        migrations.CreateModel(
            name="RegistioElectrico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "electrico_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitud Poste"
                    ),
                ),
                (
                    "electrico_lon",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitud Poste"
                    ),
                ),
                (
                    "electrico_no_poste",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Identificacion Poste",
                    ),
                ),
                (
                    "electrico_comentario",
                    models.TextField(blank=True, null=True, verbose_name="Comentario"),
                ),
                (
                    "electrico_imagen1",
                    models.ImageField(upload_to="sitios/", verbose_name="Imagen Poste"),
                ),
                (
                    "electrico_imagen2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sitios/",
                        verbose_name="Imagen Electrico",
                    ),
                ),
                (
                    "electrico_img_google",
                    models.ImageField(blank=True, null=True, upload_to="imgs_gmap/"),
                ),
                (
                    "candidato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registros.candidato",
                    ),
                ),
            ],
        ),
    ]
