# Generated by Django 4.2.11 on 2024-04-18 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_candidato_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AddField(
            model_name='candidato',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registros.usuario'),
            preserve_default=False,
        ),
    ]
