# Generated by Django 4.2.11 on 2024-04-07 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0005_registrollegada_registrolocalidad_servicio_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrollegada',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llegada_sitio', to='registros.sitio'),
        ),
        migrations.AlterField(
            model_name='registrollegada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llegada_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrolocalidad',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_sitio', to='registros.sitio'),
        ),
        migrations.AlterField(
            model_name='registrolocalidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
