# Generated by Django 4.2.11 on 2024-04-07 20:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0006_alter_registrollegada_sitio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('propietario_nombre_apellido', models.CharField(max_length=100)),
                ('propietario_born', models.DateTimeField()),
                ('propietario_ci', models.CharField(blank=True, max_length=15, null=True)),
                ('propietario_telf', models.CharField(max_length=15)),
                ('propietario_direccion', models.TextField(max_length=100)),
                ('propietario_estado_civil', models.BooleanField(default=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_sitio', to='registros.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
