# Generated by Django 4.2.11 on 2024-04-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "registros",
            "0006_registropropiedad_registropropietario_registrositio_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registioelectrico",
            name="id",
        ),
        migrations.AlterField(
            model_name="registioelectrico",
            name="candidato",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="registros.candidato",
            ),
        ),
    ]
