# Generated by Django 4.2.11 on 2024-04-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_candidato_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='a', max_length=120),
            preserve_default=False,
        ),
    ]
