# Generated by Django 4.2.11 on 2024-04-07 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0007_registropropietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propiedad_rol', models.CharField(max_length=100)),
                ('propiedad_escritura', models.CharField(max_length=15)),
                ('propiedad_registro_civil', models.TextField(max_length=100)),
                ('propiedad_imagen', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('propiedad_descripcion', models.TextField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedad_candidato', to='registros.registropropietario')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedad_sitio', to='registros.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedad_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
