# Generated by Django 4.2.11 on 2024-04-22 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0007_remove_registioelectrico_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrolocalidad",
            name="sitio",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="registros.sitio",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registrolocalidad",
            name="candidato",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="registros.candidato",
            ),
        ),
    ]
