# Generated by Django 4.2.11 on 2024-04-18 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_alter_registrolocalidad_candidato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'Registro Campo', 'verbose_name_plural': 'Registros Campo'},
        ),
        migrations.AlterModelOptions(
            name='registrolocalidad',
            options={'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterField(
            model_name='registrollegada',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato', unique=True),
        ),
        migrations.AlterField(
            model_name='registrolocalidad',
            name='candidato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato'),
        ),
    ]
