# Generated by Django 4.2.11 on 2024-04-18 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_alter_candidato_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrollegada',
            name='candidato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato'),
        ),
    ]
