# Generated by Django 4.2.11 on 2024-04-21 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0008_sitio_img_google"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrollegada",
            options={
                "verbose_name": "Llegada Localidad",
                "verbose_name_plural": "Llegada Localidad",
            },
        ),
        migrations.AlterModelOptions(
            name="registrolocalidad",
            options={"verbose_name": "Localidad", "verbose_name_plural": "Localidad"},
        ),
        migrations.AlterModelOptions(
            name="registropropietario",
            options={
                "verbose_name": "Propietario",
                "verbose_name_plural": "Propietario",
            },
        ),
        migrations.AddField(
            model_name="registrositio",
            name="sitio_img_google",
            field=models.ImageField(blank=True, null=True, upload_to="imgs_gmap/"),
        ),
        migrations.AlterField(
            model_name="registrollegada",
            name="fecha_llegada",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de llegada"
            ),
        ),
        migrations.AlterField(
            model_name="registrollegada",
            name="status_llegada",
            field=models.CharField(
                choices=[
                    ("ok", "Llegada al lugar"),
                    ("in", "incidente"),
                    ("no", "No Llegada"),
                ],
                default="ok",
                max_length=10,
                verbose_name="Estatus",
            ),
        ),
        migrations.AlterField(
            model_name="registropropiedad",
            name="propiedad_rol",
            field=models.CharField(max_length=100, verbose_name="Rol"),
        ),
        migrations.AlterField(
            model_name="registropropietario",
            name="propietario_estado_civil",
            field=models.BooleanField(default=True, verbose_name="Estado Civil"),
        ),
        migrations.AlterField(
            model_name="registropropietario",
            name="propietario_nombre_apellido",
            field=models.CharField(max_length=100, verbose_name="Nombre y Apellido"),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="PTICellID",
            field=models.CharField(max_length=15, verbose_name="Cell ID"),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="img_google",
            field=models.ImageField(blank=True, null=True, upload_to="imgs_gmap/"),
        ),
    ]
