# Generated by Django 4.2.11 on 2024-04-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0009_alter_registrollegada_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registioelectrico",
            name="electrico_img_google",
            field=models.ImageField(blank=True, null=True, upload_to="imgs_gmap/"),
        ),
    ]
