# Generated by Django 4.2.11 on 2024-04-18 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_alter_registrollegada_candidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario_nombre_apellido', models.CharField(max_length=100)),
                ('propietario_born', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('propietario_ci', models.CharField(blank=True, max_length=15, null=True, verbose_name='Documento de Identidad')),
                ('propietario_telf', models.CharField(max_length=15, verbose_name='Telefono de Contacto')),
                ('propietario_direccion', models.TextField(max_length=100, verbose_name='Direccion Domicilio')),
                ('propietario_estado_civil', models.BooleanField(default=True, verbose_name='Casado')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
    ]
