# Generated by Django 4.2.11 on 2024-04-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0009_remove_registrolocalidad_sitio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrolocalidad",
            name="sitio",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="registros.sitio",
            ),
            preserve_default=False,
        ),
    ]
