# Generated by Django 4.2.11 on 2024-04-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0010_registrolocalidad_sitio"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrolocalidad",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registrolocalidad",
            name="candidato",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registros.candidato",
            ),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="contador_llegadas",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Registro/Candidato"
            ),
        ),
    ]
