# Generated by Django 4.2.11 on 2024-04-07 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0010_registrositioimagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropropietario',
            name='candidato',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.CreateModel(
            name='RegistioElectrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrico_lat', models.FloatField(blank=True, null=True)),
                ('electrico_lon', models.FloatField(blank=True, null=True)),
                ('electrico_no_poste', models.CharField(blank=True, max_length=10, null=True)),
                ('electrico_comentario', models.TextField(blank=True, null=True)),
                ('electrico_imagen1', models.ImageField(upload_to='sitios/')),
                ('electrico_imagen2', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='registros.registropropietario')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrico_sitio', to='registros.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrico_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
