# Generated by Django 4.2.11 on 2024-04-07 22:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_alter_registropropietario_candidato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': 'Pais Empresa'},
        ),
        migrations.RemoveField(
            model_name='registrositio',
            name='candidato',
        ),
        migrations.AddField(
            model_name='registrollegada',
            name='candidato',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='registrolocalidad',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='localidad_candidato', to='registros.registrollegada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrositio',
            name='candidado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sitio_candidato', to='registros.registrollegada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registioelectrico',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrico_candidato', to='registros.registrollegada'),
        ),
        migrations.AlterField(
            model_name='registropropiedad',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedad_candidato', to='registros.registrollegada'),
        ),
        migrations.AlterField(
            model_name='registropropietario',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_candidato', to='registros.registrollegada'),
        ),
    ]
