# Generated by Django 4.2.11 on 2024-04-18 01:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_registropropiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio_fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Visita')),
                ('sitio_lat', models.FloatField(blank=True, null=True, verbose_name='Latitud Torre')),
                ('sitio_lon', models.FloatField(blank=True, null=True, verbose_name='Longitud Torre')),
                ('sitio_imagen', models.ImageField(blank=True, null=True, upload_to='sitios/')),
                ('sitio_descripcion', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
            options={
                'verbose_name': 'Registro Sitio',
                'verbose_name_plural': 'Registro Sitios',
            },
        ),
    ]
