# Generated by Django 4.2.11 on 2024-04-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_alter_servicio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrositio',
            name='sitio_imagen',
        ),
        migrations.AlterField(
            model_name='registropropiedad',
            name='propiedad_escritura',
            field=models.CharField(max_length=100),
        ),
    ]
