# Generated by Django 4.2.11 on 2024-04-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_registrositio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSitioImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='fotografias/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
            options={
                'verbose_name': 'Imagen Sitio',
                'verbose_name_plural': 'Imagenes Sitios',
            },
        ),
    ]
