# Generated by Django 4.2.11 on 2024-04-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0013_alter_registrolocalidad_candidato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrolocalidad",
            name="sitio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="registros.sitio"
            ),
        ),
    ]
