# Generated by Django 4.2.11 on 2024-04-08 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0013_remove_registrositio_sitio_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrositioimagenes',
            name='registrositio',
        ),
        migrations.AddField(
            model_name='registrositio',
            name='sitio_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrositio',
            name='sitio_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sitios/'),
        ),
        migrations.AddField(
            model_name='registrositioimagenes',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sitio_imagenes_candidato', to='registros.registrollegada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrositioimagenes',
            name='sitio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sitio_imagenes_sitio', to='registros.sitio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrositioimagenes',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sitio_imagenes_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
