# Generated by Django 4.2.11 on 2024-04-27 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registros", "0013_alter_registrositioimagenes_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="registioelectrico",
            name="usuario",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registioelectrico",
            name="electrico_comentario",
            field=models.TextField(default=1, verbose_name="Comentario"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registioelectrico",
            name="electrico_lat",
            field=models.FloatField(default=1, verbose_name="Latitud Poste"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registioelectrico",
            name="electrico_lon",
            field=models.FloatField(default=1, verbose_name="Longitud Poste"),
            preserve_default=False,
        ),
    ]
