# Generated by Django 4.2.11 on 2024-04-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_registrositioimagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrositioimagenes',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato'),
        ),
    ]
