# Generated by Django 4.2.11 on 2024-04-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_remove_registrositioimagenes_registrositio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='pais_empresa',
            new_name='servicio',
        ),
    ]
