# Generated by Django 4.2.11 on 2024-04-18 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_alter_registrositioimagenes_candidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistioElectrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrico_lat', models.FloatField(blank=True, null=True, verbose_name='Latitud Poste')),
                ('electrico_lon', models.FloatField(blank=True, null=True, verbose_name='Longitud Poste')),
                ('electrico_no_poste', models.CharField(blank=True, max_length=10, null=True, verbose_name='Identificacion Poste')),
                ('electrico_comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('electrico_imagen1', models.ImageField(upload_to='sitios/', verbose_name='Imagen Poste')),
                ('electrico_imagen2', models.ImageField(blank=True, null=True, upload_to='sitios/', verbose_name='Imagen Electrico')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato')),
            ],
        ),
    ]
