# Generated by Django 4.2.11 on 2024-04-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_rename_pais_empresa_usuario_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='servicio',
            new_name='pais_empresa',
        ),
    ]
