# Generated by Django 4.2.11 on 2024-04-18 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_registioelectrico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrolocalidad',
            name='imagen_maps',
        ),
        migrations.AlterField(
            model_name='registioelectrico',
            name='candidato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registros.candidato'),
        ),
    ]
