# Generated by Django 4.2.11 on 2024-04-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0016_rename_servicio_usuario_pais_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitio',
            old_name='servicio',
            new_name='pais_empresa',
        ),
    ]
