# Generated by Django 4.2.11 on 2024-04-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0017_rename_servicio_sitio_pais_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
