# Generated by Django 4.2.11 on 2024-04-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "registros",
            "0018_alter_registrositio_options_registioelectrico_sitio_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroSitioImagenes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.FileField(upload_to="fotografias/")),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registros.candidato",
                    ),
                ),
                (
                    "sitio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registros.sitio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen Sitio",
                "verbose_name_plural": "Imagenes Sitios",
            },
        ),
    ]
