# Generated by Django 4.2.11 on 2024-04-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0021_alter_registioelectrico_candidato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registioelectrico",
            name="candidato",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="registros.candidato",
            ),
        ),
    ]
