# Generated by Django 4.2.11 on 2024-04-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0022_alter_registioelectrico_candidato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrositioimagenes",
            name="candidato",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registros.candidato",
            ),
        ),
    ]
