# Generated by Django 4.2.11 on 2024-04-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0025_remove_registrositioimagenes_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrositioimagenes",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registrositioimagenes",
            name="candidato",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registros.candidato",
            ),
        ),
    ]
