# Generated by Django 4.2.11 on 2024-04-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0027_alter_registrositioimagenes_candidato"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrollegada",
            options={"verbose_name": "Llegada", "verbose_name_plural": "Llegadas"},
        ),
        migrations.AlterModelOptions(
            name="registrolocalidad",
            options={"verbose_name": "Localidad", "verbose_name_plural": "Localidades"},
        ),
        migrations.AlterModelOptions(
            name="registropropietario",
            options={
                "verbose_name": "Propietario",
                "verbose_name_plural": "Propietario",
            },
        ),
        migrations.AddField(
            model_name="sitio",
            name="img_google",
            field=models.ImageField(blank=True, null=True, upload_to="imgs_gmap/"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="candidato",
            field=models.CharField(
                blank=True,
                max_length=15,
                primary_key=True,
                serialize=False,
                verbose_name="Registro",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre",
            field=models.CharField(max_length=25, verbose_name="Empresa"),
        ),
    ]
