# Generated by Django 4.2.11 on 2024-04-24 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0028_alter_registrollegada_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registropropiedad",
            options={"verbose_name": "Propiedad", "verbose_name_plural": "Propiedades"},
        ),
        migrations.AlterModelOptions(
            name="registropropietario",
            options={
                "verbose_name": "Propietario",
                "verbose_name_plural": "Propietarios",
            },
        ),
    ]
