# Generated by Django 4.2.11 on 2024-04-24 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0029_alter_registropropiedad_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrositio",
            old_name="sitio_img_google",
            new_name="img_google_dist_nominal",
        ),
    ]
