# Generated by Django 4.2.11 on 2024-04-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registros",
            "0030_rename_sitio_img_google_registrositio_img_google_dist_nominal",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registrositio",
            name="img_google_sitio",
            field=models.ImageField(blank=True, null=True, upload_to="imgs_gmap/"),
        ),
    ]
