# Generated by Django 4.2.11 on 2024-04-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0031_registrositio_img_google_sitio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrositioimagenes",
            options={
                "verbose_name": "Imagen Sitio",
                "verbose_name_plural": "Imagenes Sitio",
            },
        ),
        migrations.AlterField(
            model_name="registioelectrico",
            name="electrico_img_google",
            field=models.ImageField(
                blank=True, null=True, upload_to="sitios/imgs_gmap/"
            ),
        ),
        migrations.AlterField(
            model_name="registrollegada",
            name="imagen_llegada",
            field=models.ImageField(blank=True, null=True, upload_to="llegada/"),
        ),
        migrations.AlterField(
            model_name="registropropiedad",
            name="propiedad_imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="sitios/propiedad"
            ),
        ),
        migrations.AlterField(
            model_name="registrositio",
            name="img_google_dist_nominal",
            field=models.ImageField(
                blank=True, null=True, upload_to="sitios/imgs_gmap/"
            ),
        ),
        migrations.AlterField(
            model_name="registrositio",
            name="img_google_sitio",
            field=models.ImageField(
                blank=True, null=True, upload_to="sitios/imgs_gmap/"
            ),
        ),
        migrations.AlterField(
            model_name="registrositioimagenes",
            name="pic",
            field=models.FileField(blank=True, null=True, upload_to="sitios/fotos/"),
        ),
    ]
