# Generated by Django 4.2.11 on 2024-04-24 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0032_alter_registrositioimagenes_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrositio",
            name="sitio_imagen",
        ),
    ]
