# Generated by Django 4.2.11 on 2024-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0033_remove_registrositio_sitio_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrollegada",
            name="status_llegada",
            field=models.BooleanField(blank=True, verbose_name="Estatus"),
        ),
    ]
