# Generated by Django 4.2.11 on 2024-04-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0034_alter_registrollegada_status_llegada"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registioelectrico",
            options={"verbose_name": "Electrico", "verbose_name_plural": "Electrico"},
        ),
        migrations.AlterModelOptions(
            name="registrollegada",
            options={"verbose_name": "Llegada", "verbose_name_plural": "Llegada"},
        ),
        migrations.AlterModelOptions(
            name="registrolocalidad",
            options={"verbose_name": "Localidad", "verbose_name_plural": "Localidad"},
        ),
        migrations.AlterModelOptions(
            name="registropropiedad",
            options={"verbose_name": "Propiedad", "verbose_name_plural": "Propiedad"},
        ),
        migrations.AlterModelOptions(
            name="registropropietario",
            options={
                "verbose_name": "Propietario",
                "verbose_name_plural": "Propietario",
            },
        ),
        migrations.AlterModelOptions(
            name="registrositio",
            options={"verbose_name": "Sitio", "verbose_name_plural": "Sitio"},
        ),
        migrations.AlterModelOptions(
            name="sitio",
            options={
                "verbose_name": "Datos Sitio",
                "verbose_name_plural": "Datos Sitio",
            },
        ),
        migrations.AlterField(
            model_name="registrollegada",
            name="status_llegada",
            field=models.CharField(blank=True, max_length=3, verbose_name="Estatus"),
        ),
    ]
