# Generated by Django 4.2.11 on 2024-04-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0035_alter_registioelectrico_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrollegada",
            name="status_llegada",
            field=models.CharField(blank=True, max_length=5, verbose_name="Estatus"),
        ),
    ]
