# Generated by Django 4.2.11 on 2024-04-25 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0036_alter_registrollegada_status_llegada"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registioelectrico",
            options={"verbose_name": "Eléctrico", "verbose_name_plural": "Eléctrico"},
        ),
    ]
