# Generated by Django 4.2.11 on 2024-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registros", "0037_alter_registioelectrico_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrollegada",
            name="status_llegada",
            field=models.CharField(
                blank=True,
                choices=[("true", "Llegada con exito"), ("false", "Incidente")],
                max_length=5,
                verbose_name="Estatus",
            ),
        ),
    ]
