# Generated by Django 4.2.11 on 2024-06-06 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "nombre",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Empresa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telf", models.CharField(max_length=15)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.empresa",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sitio",
            fields=[
                (
                    "PTICellID",
                    models.CharField(
                        max_length=17, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100)),
                (
                    "lat_nominal",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitud Nominal"
                    ),
                ),
                (
                    "lon_nominal",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitud Nominal"
                    ),
                ),
                ("altura", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "provincia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Provincia/Region",
                    ),
                ),
                ("municipio", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "localidad",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Localidad/Comuna",
                    ),
                ),
                (
                    "img_google",
                    models.ImageField(blank=True, null=True, upload_to="imgs_gmap/"),
                ),
                (
                    "contador_llegadas",
                    models.PositiveIntegerField(default=0, verbose_name="Reg./Cand."),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sitios",
                        to="main.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sitios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitio",
                "verbose_name_plural": "Sitios",
            },
        ),
    ]
