# Generated by Django 4.2.11 on 2024-04-25 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="principal",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="principal",
            name="imagen",
        ),
    ]
