# Generated by Django 4.2.11 on 2024-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_siteconfiguration_delete_principal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="token_gmaps",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key de Google Maps, para generar imagenes satelitales en los reporte",
                max_length=100,
                null=True,
                verbose_name="Token de Google Maps",
            ),
        ),
    ]
